workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    working_directory: app
    integrations:
      app_store_connect: Codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.cardscontrol.app
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.cardscontrol.app"
    scripts:
      - name: Clean and get Flutter packages
        script: |
          flutter clean
          rm -rf pubspec.lock
          flutter pub get
      - name: Regenerate iOS project
        script: |
          rm -rf ios/Pods ios/Podfile.lock
          flutter build ios --config-only --release --no-codesign
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install --repo-update
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$PROJECT_BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false

  android-release:
    name: Android Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    working_directory: app
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build AAB
        script: |
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/*.aab
